[versions]
# libraries
remote-robot = "0.11.23"
kotlin = "2.3.20-ij253-64"
junit-jupiter = "5.12.2"

# plugins
sonarqube = "5.1.0.4882"

[libraries]
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
remote-robot = { group = "com.intellij.remoterobot", name = "remote-robot", version.ref = "remote-robot" }
remote-fixtures = { group = "com.intellij.remoterobot", name = "remote-fixtures", version.ref = "remote-robot" }

[plugins]
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }